#!/bin/sh

cd ../winsup/cygwin || cd winsup/cygwin || {
    echo "Could not cd to winsup/cygwin" >&2;
    exit 1;
}


for header in hack.h path.h
do
    for file in *.cc; do
        if grep -q "$header" "$file"; then
            if [ "$header" -nt "$file" ]; then
                touch "$file"
            fi
        fi
    done
done
